### ISSUE TITLE
Please add this to readme

### ISSUE THREAD

**Issue by salinaaaaaa** [udacity/CVND_Exercises#18]
If you have an NVIDIA GPU and want a fully functional GPU enabled environment, you can try this Docker container below. It is fully supported by the author and you can ask questions on how to install or follow the detailed readme:

https://github.com/joehoeller/NVIDIA-GPU-Tensor-Core-Accelerator-PyTorch-OpenCV

**Comment by joehoeller** [comment]
** Friendly Bump ** @igrigorik @sodabrew @13rac1 @ivikash

**Comment by 13rac1** [comment]
@joehoeller Sorry, I cannot review this PR. I did not create this content.

**Comment by joehoeller** [comment]
I created it and support it. I’m offering it as an option for those that have GPUs locally, or access in cloud in their own.
