### ISSUE TITLE
weights folder is missing from YOLO exercise

### ISSUE THREAD

**Issue by Bjarten** [udacity/CVND_Exercises#4]
https://github.com/udacity/CVND_Exercises/blob/15963e23035b6ecf18dc484f635e2646bae9b6b0/2_2_YOLO/YOLO.ipynb#L84

**Comment by roachsinai** [comment]
Check this webpage https://pjreddie.com/darknet/yolo/, which said provide a weight at  `wget wget https://pjreddie.com/media/files/yolov3.weights`.

I'm downloading the weight, but the net speed is low in my country to access that file.
