### ISSUE TITLE
I think There is a mistake in a notebook

### ISSUE THREAD

**Issue by Titorat** [udacity/CVND_Exercises#6]
1_1_Image_Representation/2. Visualizing RGB Channels.ipynb

In this file the last cell. cmap are set to gray where they should be set to Reds, Greens,Blues, respectively.

**Comment by AVI18794** [comment]
@Titorat  I think you are right as we are supposed to visualize the three different channels of the image seperately. How do find which areas are having minimum and maximum values of the respective channels. Min and maximum values I can find but which areas are having that values how to find and plot that.
